### ISSUE TITLE
Not enough memory error

### ISSUE THREAD

**Issue by DotTheI** [oxguy3/subtitle-edit-launcher#1]
Keep getting this error every time I start the application even thought there is some 8 GB of free RAM

![2017-11-23 17 46 53](https://user-images.githubusercontent.com/10737439/33179281-eb73665c-d079-11e7-857c-893d658199ac.png)

**Comment by hayleox** [comment]
Hmm, could you try running SubtitleEdit in a terminal to see if there's any
further messages? Open macOS's Terminal and run this command (assuming you
installed Wine Stable as recommended):

/Applications/Wine\ Stable.app/Contents/Resources/wine/bin/wine "~/Library/Application Support/io.schiff.subtitleedit.maclauncher/SubtitleEdit/SubtitleEdit.exe"

(hopefully I got that command right - currently on mobile so I can't test)

**Comment by DotTheI** [comment]
@oxguy3 I got:

_wine: cannot find '~/Library/Application Support/io.schiff.subtitleedit.maclauncher/SubtitleEdit/SubtitleEdit.exe'_

**Comment by DotTheI** [comment]
Stumbled upon https://www.codeweavers.com/compatibility/crossover/tips/subtitle-edit/systemoutofmemoryexception-out-of-memory Thought it might be helpful in resolving the issue.

**Comment by DotTheI** [comment]
I reinstalled Wine with 64-bit support, and now I'm not getting the error. However, the interface of Subtitle Edit is quite distorted
![screen shot 2017-12-31 at 16 37 55](https://user-images.githubusercontent.com/10737439/34461910-f87dcabc-ee48-11e7-8866-68b99d18c63b.png)
